trigger:
  branches:
    include:
      - main

pool:
  name: Default

variables:
  pythonVersion: '3.10'

steps:
  # ----------------------------
  # Checkout
  # ----------------------------
  - checkout: self
    clean: true

  # ----------------------------
  # Run unit tests with coverage
  # ----------------------------
  - script: |
      source /Users/ctac/Library/Caches/pypoetry/virtualenvs/my-sbit-project-eXtul0LL-py3.11/bin/activate
      poetry run pytest \
        --cov=my_sbit_project \
        --cov-report=xml \
        --cov-report=term \
        --junitxml=pytest_results.xml
    displayName: 'Run PySpark unit tests with coverage'

  # ----------------------------
  # Publish test results
  # ----------------------------
  - task: PublishTestResults@2
    displayName: 'Publish pytest results'
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/pytest_results.xml'
      mergeTestResults: true

  # ----------------------------
  # Publish code coverage
  # ----------------------------
  - task: PublishCodeCoverageResults@2
    displayName: 'Publish code coverage'
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: 'coverage.xml'