[project]
name = "my_sbit_project"
version = "1.2.5"
description = "My end to end Azure and Databricks project"
authors = [
    {name = "StephanKnox",email = "stanislav.i.kulchitskiy@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml (>=6.0.2,<7.0.0)",
    "pyspark (==3.5.2)",
    "pytest (>=8.4.1,<9.0.0)",
    "delta-spark (==3.2.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sbit-launcher = "my_sbit_project.run_main:main"
