[project]
name = "my_sbit_project"
version = "1.3.1"
description = "My end to end Azure and Databricks project"
authors = [
    {name = "StephanKnox",email = "stanislav.i.kulchitskiy@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyyaml (==6.0.2)",
    "pyspark (==3.5.2)",
    "pytest (==8.4.1)",
    "delta-spark (==3.2.0)",
    "pytest-mock (==3.15.1)",
    "pytest-cov (>=7.0.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
sbit-launcher = "my_sbit_project.run_main:main"
sbit-backfill = "my_sbit_project.run_backfill:main"
